<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
	</array>
	<key>name</key>
	<string>Ansible</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.ansible</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.line.ansible</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*((#).*)</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.ansible.jinja</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?:True|False|yes|no|None)\b</string>
			<key>name</key>
			<string>constant.language.ansible</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?:not)\b</string>
			<key>name</key>
			<string>keyword.operator.ansible</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.ansible</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ansible</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(?:- )?(name|include):\s+(.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.ansible</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.jinja</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.ansible.jinja</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.function.ansible.jinja</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(when):\s+([a-zA-z][\w\.]+)\s*(\|)\s*(failed|changed|success|skipped)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.ansible</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(?:- )?(?!name|include)(\w+):\s</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.ansible</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)=</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\"</string>
					<key>end</key>
					<string>\"|$</string>
					<key>name</key>
					<string>string.quoted.double.ansible</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.jinja.ansible</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\'</string>
					<key>end</key>
					<string>\'|$</string>
					<key>name</key>
					<string>string.quoted.single.ansible</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.jinja.ansible</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ansible</string>
	<key>uuid</key>
	<string>fbfde362-bbb1-4d7d-b09d-9dce71c9bd40</string>
</dict>
</plist>
