<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
	</array>
	<key>name</key>
	<string>Jinja Expressions</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.jinja.delimiter.variable</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.jinja</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.jinja.delimiter.variable</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\{\{)\s*([a-zA-z][\w\.]+)\s*(\}\})</string>
			<key>name</key>
			<string>meta.scope.expression.jinja</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{\{)\s*(?:([a-zA-z][\w\.]+)\s*(\|))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.jinja.delimiter.variable</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.jinja</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.jinja</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.other.jinja.delimiter.variable</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.scope.expression.jinja</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\"</string>
					<key>end</key>
					<string>\"|$</string>
					<key>name</key>
					<string>string.quoted.double.ansible.jinja</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\'</string>
					<key>end</key>
					<string>\'|$</string>
					<key>name</key>
					<string>string.quoted.single.ansible.jinja</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\d+(?:\.\d+)\b</string>
					<key>name</key>
					<string>constant.numeric.jinja</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(abs|attr|batch|capitalize|center|default|dictsort|escape|filesizeformat|first|float|forceescape|format|groupby|indent|int|join|last|length|list|lower|map|pprint|random|reject|rejectattr|replace|reverse|round|safe|select|selectattr|slice|sort|string|striptags|sum|title|trim|truncate|upper|urlencode|urlize|wordcount|wordwrap|xmlattr|callable|defined|divisibleby|equalto|escaped|even|iterable|lower|mapping|none|number|odd|sameas|sequence|string|undefined|upper|range|lipsum|dict|cycler|reset|next|current|joiner)\b</string>
					<key>name</key>
					<string>support.function.builtin.jinja</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(failed|changed|success|skipped|b64decode|b64encode|basename|checksum|default|difference|dirname|expanduser|from_json|from_yaml|hash|intersect|ipaddr|ipaddr|ipv4|ipv6|isnan|join|log|log|mandatory|max|min|password_hash|pow|random|random|realpath|regex_escape|regex_replace|relpath|root|root|shuffle|splitext|symmetric_difference|ternary|to_json|to_nice_json|to_nice_yaml|to_uuid|to_yaml|union|unique|version_compare)\b</string>
					<key>name</key>
					<string>support.function.ansible.jinja</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:True|False|yes|no|None)\b</string>
					<key>name</key>
					<string>constant.language.ansible</string>
				</dict>
				<dict>
					<key>match</key>
					<string>~|\||==|!=|&lt;=?|&gt;=?|\+|-|//?|%|\*\*?</string>
					<key>name</key>
					<string>keyword.operator.ansible.jinja</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(in|is|and|or|not)\b</string>
					<key>name</key>
					<string>keyword.operator.ansible.jinja</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.jinja.ansible</string>
	<key>uuid</key>
	<string>f1b9db88-d5a0-4ca3-8da3-df4617983f0f</string>
</dict>
</plist>
